### ISSUE TITLE
File main.mk is missing

### ISSUE THREAD

**Issue by rfalke** [Cararasu/holodec#2]
```----------Building project:[ main - Debug ]----------
make[1]: Entering directory 'holodec-git/main'
make[1]: main.mk: No such file or directory
make[1]: *** No rule to make target 'main.mk'.  Stop.
make[1]: Leaving directory 'holodec-git/main'
Makefile:4: recipe for target 'All' failed
make: *** [All] Error 2
```

**Comment by Cararasu** [comment]
Yeah, well atm I am using this repository for development. It is by no means finished. If I come close to a runnable program, then I will invest some time in making it compilable by everyone ;-)
But the way things are, that will still take some time.

**Comment by p3rtinax** [comment]
@Cararasu,
Dear Cararasu,
Is it not ready compatible for everyone yet?
same error,

how to build it? please help 
thanks

**Comment by Cararasu** [comment]
Sry for the late answer I was busy the last few days.

Well the problem is that I used this repository as a developement repo for myself. For now I did not really concern myself with making it easily buildable for everyone. Sorry about that.
Oh I just remembered maybe I should add a licence so people can actually use the code legally. Hmm...

Also making it compilable for everyone was not a priority because, unfortunately as the developement went on I discovered a few fundamental flaws in my design that would need major rewrites to the whole system. At the moment the decompiler can handle simple programs but anything complicated will be completely unreadable.
Therefore it is sadly not really in a usable state. I can for now not make those fundamental changes because of time issues but I plan on updating the README in the next few days/weeks with what I have learned and maybe ideas on how to improve it in case any other poor soul also tries his/her hand at writing a decompiler.

**Comment by Cararasu** [comment]
Btw I found the main.mk file and pushed it.
The decompielr does not produce good results but at least it should be compilable now

**Comment by alamerrouka** [comment]
how can i use it

**Comment by Cararasu** [comment]
@alamerrouka You should be able to compile it with `make` but I did not have the time to work on this project for years now and it is by far not finished. I doubt I will pick it back up again.
If you want to use an actual working decompiler I can recommend ghidra or if you have the money IDA Pro. They both work well once you have gotten used to their interface.

**Comment by alamerrouka** [comment]
> @alamerrouka You should be able to compile it with `make` but I did not have the time to work on this project for years now and it is by far not finished. I doubt I will pick it back up again.
> If you want to use an actual working decompiler I can recommend ghidra or if you have the money IDA Pro. They both work well once you have gotten used to their interface.

thank you bro❤❤
